version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: |
          npm install
          npm run test
workflows:
  version: 2
  test:
    jobs:
      - test